### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by LarryBarker** [Matildevoldsen/course-platform#12]
Hello 👋  first, thank you for your YouTube series! Very thorough and informative. I've cloned the repo, and set everything up as best I know how. I'm running in to CSRF mismatch errors when trying to register and/or login.

Did you have this issue? I'm a bit lost on what to do next. Here's what I have done:

1. Cloned repo
2. Installed backend and frontend dependencies
3. Setup database
4. Generated `APP_KEY`
4. Changed `SESSION_DRIVER` to `cookie`
5. Added `SESSION_DOMAIN` as `localhost`

Any feedback at your convenience is greatly appreciated! Thanks much 😄

**Comment by Matildevoldsen** [comment]
Hi Larry Barker,

Did you fix the issue yet? Otherwise, can you give the exact error message?

Sorry for being a bit slow at getting back to you on the issue

**Comment by LarryBarker** [comment]
No worries, thanks for the reply!

No I don’t think I did. I’ll have to pull the project back up and see
exactly what it was again.
